--PRODUCTS TABLE SUMMARY
--HOW MANY TOTAL PRODUCTS IN PRODUCTS TABLE? (9977)
SELECT COUNT(*)
FROM PRODUCTS

--HOW MANY TOTAL VENDORS AND CATEGORIES IN SALES TABLE? (271 VENDORS, 69 CATEGORIES OF PRODUCT)
SELECT COUNT (DISTINCT VENDOR), COUNT(DISTINCT CATEGORY_NAME)
FROM PRODUCTS

--SALES TABLE SUMMARY
--WHICH PRODUCT SELLS THE BEST/WORST IN TOTAL SALES (BLACK VELVET CANADIAN WHISKEY=BEST, NEW AMSTERDAM CITRON=WORST)

SELECT CATEGORY_NAME, DESCRIPTION, SUM (TOTAL)
FROM SALES
GROUP BY CATEGORY_NAME, DESCRIPTION
ORDER BY SUM(TOTAL) DESC

--COUNTIES TABLE SUMMARY
--WHAT AREAS OF THE STATE SELL MORE LIQUOR THAN OTHERS (COUNT) (POLK, LINN AND SCOT...LEFT JOIN SHOWS ALL COUNTIES HAVE AT LEAST ONE SALE)

SELECT A.COUNTY, COUNT(B.*)
FROM COUNTIES A LEFT JOIN SALES B USING (COUNTY)
GROUP BY A.COUNTY
ORDER BY 2 DESC

--RANKING TOTAL SALES BY COUNTY TO FIND RANGE OF SALES PERFORMANCE (IN ORDER TO STRATIFY COUNTY SALES BY SMALL V. MID V. LARGE MARKET)

SELECT A.COUNTY, SUM (A.TOTAL)
FROM SALES A
GROUP BY A.COUNTY
ORDER BY 2 ASC;

---FIND MAX COUNTY SALES, SUBTRACT MIN COUNTY SALES TO FIND RANGE OF SALES, DIVIDE BY 3 TO GET SMALL, MEDIUM, LARGE MARKET WIDTH

  SELECT (86397461 - 16603)/3 AS SALES_BUCKET_SIZE;

--CALCULATIONS FOR CASE STATEMENT (TAKING SUBTRACTION FROM LINE ABOVE AND ADDING IT TO MIN SALES AMOUNT TO BUCKET #S FOR CASE STATEMENT

SELECT 16603.67 + 28793619;
SELECT 28810222.67 + 28793619;

/*REALIZED TAKING THE RANGE OF SALES BETWEEN TOP AND BOTTOM COUNTIES, THEN DIVIDING EVENLY BY 3 WOULD PUT VIRTUALLY
ALL COUNTIES IN THE SMALL BUCKET SO DECIDED TO COUNT ALL COUNTIES INSTEAD (100) AND THEN DIVIDE BY 3 TO STRATIFY SALES */

SELECT 100/3 AS INTERVAL_FOR_SALES_BUCKETS;

--CASE FUNCTION TO PUT SALES/CAPITA BY COUNTY INTO SMALL/MEDIUM/LARGE MARKET BUCKETS

SELECT A.COUNTY, ROUND((SUM (A.TOTAL)/B.POPULATION)) AS SALES_PER_CAPITA
, CASE WHEN ROUND ((SUM(A.TOTAL)/B.POPULATION),2) <= 65.76 THEN 'SMALL'
	 WHEN ROUND ((SUM(A.TOTAL)/B.POPULATION),2) <= 99.93 THEN 'MID'
	 ELSE 'LARGE'
	 END AS MARKET_SIZE
FROM SALES A
INNER JOIN COUNTIES B
USING (COUNTY)
WHERE COUNTY IS NOT NULL
GROUP BY A.COUNTY, B.POPULATION
ORDER BY 2 ASC;

--DECIDED TO TAKE BOTTOM 10% OF SMALL REVENUE/CAPITA COUNTIES (3) AS INTIAL TARGET, BUT THEN LOOK AT LIQUOR TYPES WITHIN COUNTIES
--PRIORITIZING TOP END OF LIQUOR TYPES WITHIN POOR PERFORMING COUNTIES (IE) ASSUMING THERE IS REASON PEOPLE IN THESE COUNTIES BUY PARTICULAR TYPES
--PERHAPS WE CAN BOOST THE POTENTIAL FOR FURTHER SALES, PUSHING THESE COUNTIES INTO MID OR HIGH LEVEL SALES PRODUCERS
--FOCUS HERE IS ON GROWTH IN SMALLER MARKETS AS OPPOSED TO INCREASING FOOTPRINT IN ESTABLISHED MARKETS

SELECT CASE WHEN CATEGORY_NAME ILIKE '%WHISK%' OR CATEGORY_NAME ILIKE '%SCOTCH%' OR CATEGORY_NAME ILIKE '%BOURB%' THEN 'WHISKEY'
			WHEN CATEGORY_NAME ILIKE '%TEQ%' THEN 'TEQUILA'
			WHEN CATEGORY_NAME ILIKE '%VODKA%' THEN 'VODKA'
			WHEN CATEGORY_NAME ILIKE '%RUM%' THEN 'RUM'
			WHEN CATEGORY_NAME ILIKE '%GIN%' THEN 'GIN'
			WHEN CATEGORY_NAME ILIKE '%SCHNA%' OR CATEGORY_NAME ILIKE '%BRAND%' OR CATEGORY_NAME ILIKE '%LIQE%' THEN 'LIQEUOR'
			ELSE 'MISCELLANEOUS'
	END AS LIQUOR_TYPE
	, SUM (TOTAL) AS SALES_TOTAL
FROM SALES
WHERE COUNTY IN ('FREMONT', 'WAYNE', 'DAVIS')
GROUP BY LIQUOR_TYPE
ORDER BY 2 DESC;

--BASED ON CODE OUTPUT ABOVE, WHISKEY AND VODKA SEEM LIKE BEST CATEGORIES TO PURSUE FOR ANALYSIS BASED ON SALES AMOUNTS
--ASSUMPTIONS MADE THAT THERE MUST BE REASON WHY WHISKEY AND VODKA PERFORM WELL (COMPARATIVELY SPEAKING) WITHIN LOW PERFORMING COUNTIES
--BRAINSTORM WAYS WE CAN TAKE THAT UNDERLYING APPETITE FOR WHISKEY/VODKA AND MARKET TO BOOST HIGH-POTENTIAL LIQUOR SALES IN THOSE COUNTIES
--NEXT STEP IS TO ANALYZE HIGH-SALES COUNTIES SPECIFICALLY LOOKING AT THINGS LIKE LIQUOR TYPE, PACKAGING, AVG PRICES, POPULATION SIZE...ETC. TO DISCOVER TRENDS/WHY THOSE COUNTIES DO WELL

--CLASSIFY THE AMOUNT OF ML PER PRODUCT SOLD (SALES TOTALS BY VOLUME).

SELECT CASE WHEN VOLUME < 7500 THEN 'LOW-VOL'
            WHEN VOLUME < 150000 THEN 'MED_VOLUME'
            ELSE 'HIGH VOLUME'
            END AS PROD_VOLUME
, SUM(TOTAL)
FROM
      (SELECT A.BOTTLE_SIZE * A.PACK * A.INNER_PACK AS VOLUME, B.TOTAL
       FROM PRODUCTS A INNER JOIN SALES B ON A.ITEM_NO=B.ITEM) AS TEMP

GROUP BY PROD_VOLUME
ORDER BY 2;

--CLASSIFY THE SALES PER CAPITA BY COUNTY

SELECT A.COUNTY, B.POPULATION, SUM (A.TOTAL), ROUND ((SUM(A.TOTAL)/B.POPULATION),2) AS SALES_PER_CAPITA
FROM SALES A
INNER JOIN COUNTIES B
USING (COUNTY)
GROUP BY A.COUNTY, B.POPULATION
ORDER BY 4 DESC;

/*ADJUSTING FOR POPULATION SIZE, NOW LOOKING FOR OTHER SMALL POPULATION COUNTIES THAT HAVE MUCH HIGHER SALES PER CAPITA

ANALYSIS: HOWARD/PALO ALTO COUNTY ARE HIGHEST PERFORMING "SMALL-SIZE COUNTY" W/ SALES_PER_CAPITA CHOSEN BECAUSE
THEY WERE THE ONLY "SMALL-POP COUNTIES" (CALCULATED BY SPLITTING ALL 99 COUNTIES IN 3RDS) THAT RANKED IN TOP 3RD OF SALES/CAPITA
WHEN LOOKING AT ALL COUNTIES, AND ADDING IN AVG BOTTLE PRICE, 9 OF TOP 10 SALES/CAPITA COUNTIES HAD AVG BOTTLE PRICES ABOVE $14 */

SELECT A.COUNTY, A.POPULATION
, CASE WHEN A.POPULATION <= 11387 THEN 'SMALL'
  WHEN A.POPULATION <= 20260 THEN 'MEDIUM'
  ELSE 'LARGE'
  END AS POP_BUCKET
  ,ROUND (SUM((B.TOTAL)/A.POPULATION),2) AS SALES_PER_CAPITA
  ,ROUND(AVG (B.BTL_PRICE::NUMERIC),2) AS AVG_BTL_PRICE
FROM COUNTIES A
INNER JOIN SALES B
USING (COUNTY)
GROUP BY A.COUNTY, A.POPULATION
ORDER BY 4 DESC


--PER STORE, WHAT PERCENTAGE OF SALES IN HOWARD/PALO ALTO COUNTY HAD BOTTLE PRICES BELOW $20 (ARBITRARY THRESHOLD FOR "MORE EXPENSIVE" VS. "LESS EXPENSIVE" BOTTLES)?

SELECT STORE, ROUND(AVG(PCT_UNDER_20),2)*100 AS
PCT_UNDER_20
FROM (

  SELECT COUNTY, STORE, TOTAL,
  CASE
  WHEN BTL_PRICE::NUMERIC < 20
  THEN 1
  ELSE 0
  END AS PCT_UNDER_20
  FROM SALES) AS TEMP
WHERE COUNTY = 'HOWARD' OR COUNTY='PALO ALTO'
GROUP BY STORE
ORDER BY 2 DESC;


--OVERALL AVG BOTTLE PRICE ACROSS COUNTIES...SEEMS LIKE PRICES UNDER $20 IS A COMMON TREND AMONG THESE SMALLER WELL-PERFORMING COUNTIES
--PRICES BELOW A CERTAIN AVG HOWEVER START TO CUT INTO SALES
--THINK ABOUT MARKETING CHEAPER WHISKEY/VODKA PRODUCTS THAT RANGE FROM $14-$17 AS SWEETSPOT

SELECT A.COUNTY, ROUND(AVG (B.BTL_PRICE::NUMERIC),2) AS AVG_BOTTLE_PRICE, COUNT (C.STORE) AS TOTAL_STORES
FROM COUNTIES A
INNER JOIN SALES B
USING (COUNTY)
INNER JOIN STORES C
USING (STORE)
GROUP BY A.COUNTY
ORDER BY 2 DESC

--WHICH COUNTIES HAVE THE HIGHEST AVG SALES OF WHISKEY OR VODKA PRODUCTS?
SELECT COUNTY, ROUND(AVG (WHISK_VODKA),2)*100 AS PCT_WHISK_VODKA
FROM (
      SELECT COUNTY, CASE WHEN CATEGORY_NAME ILIKE '%WHISK%' OR CATEGORY_NAME ILIKE '%VODKA%' THEN 1
      ELSE 0 END AS WHISK_VODKA FROM SALES) AS TEMP
GROUP BY COUNTY
ORDER BY 2 DESC

--NOW LET'S LOOK AT OUR SALES BY DIFFERENT DATE RANGES TO FIND TRENDS
--FIND LOWER/UPPER DATE LIMITS (WORKING WITH DATA FROM 2014-2015)

SELECT MIN(DATE) AS FIRST_SALE_DATE, MAX(DATE) AS LAST_SALE_DATE, AGE(MIN(DATE),MAX(DATE)) AS DATE_RANGE
FROM SALES;

--FIND SALES BY QUARTER

SELECT CASE WHEN TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM-DD') BETWEEN '2014-01-01' AND '2014-04-01' THEN '2014-Q1'
            WHEN TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM-DD') BETWEEN '2014-04-01' AND '2014-07-01' THEN '2014-Q2'
            WHEN TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM-DD') BETWEEN '2014-07-01' AND '2014-10-01' THEN '2014-Q3'
            WHEN TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM-DD') BETWEEN '2014-10-01' AND '2015-01-01' THEN '2014-Q4'
            ELSE '2015'
            END AS QUARTER_SALES
, SUM(TOTAL)
FROM SALES
GROUP BY QUARTER_SALES
ORDER BY 1

--FIND SALES BY MONTH NOW

SELECT TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM') AS SALES_MO
, SUM(TOTAL)
FROM SALES
WHERE TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM') NOT ILIKE '%2015%'
GROUP BY SALES_MO
ORDER BY 2 DESC

--ABOVE QUERY SEEMS TO INDICTE THAT MARKETING AROUND HOLIDAYS MAY NOT BE AS LUCRATIVE AS ANTICIPATED
--PERHAPS TARGET MONTHS LIKE APRIL, MAY, JAN, MARCH, FEB (IN THAT ORDER)
--LET'S CHECK IF BOTTLE_PRICE RANGES FLUCTUATE ACROSS THE MONTHS

SELECT TO_CHAR(DATE_TRUNC('MONTH', DATE),'YYYY-MM') AS SALES_MO
, SUM(TOTAL)
, CASE WHEN BTL_PRICE::NUMERIC BETWEEN 0 AND 14 THEN 'CHEAP'
       WHEN BTL_PRICE::NUMERIC BETWEEN 14 AND 25 THEN 'MID-TIER'
       WHEN BTL_PRICE::NUMERIC > 25 THEN 'EXPENSIVE'
       END AS PRICE_RANGE
FROM SALES
GROUP BY SALES_MO, PRICE_RANGE
ORDER BY 1

--ABOVE QUERY SHOWS FLUCTUATION IS MINOR AMONG PRICE RANGE

/*WHICH COUNTY SOLD THE MOST (TOTAL VOLUME) AMOUNT OF VODKA DURING FEBRUARY 2014? IS
THIS AMONG THE COUNTIES THAT SOLD THE MOST VODKA IN OTHER MONTHS OF 2014
AS WELL? */

SELECT COUNTY, SUM(VOLUME)
FROM
   (SELECT A.*, B.BOTTLE_SIZE*B.PACK*B.INNER_PACK AS VOLUME
    FROM SALES A
    INNER JOIN PRODUCTS B
    ON A.ITEM=B.ITEM_NO) AS TEMP
WHERE TEMP.CATEGORY_NAME ILIKE '%VODKA%' AND TO_CHAR(DATE_TRUNC('MONTH',TEMP.DATE),'YYYY-MM') ILIKE '%2014-02%'
GROUP BY COUNTY
ORDER BY 2 DESC

--WHICH COUNTIES HAVE THE HIGHEST SALE OF ITEMS HIGHER THAN 80 PROOF?

SELECT COUNTY, ROUND(AVG(OVER_80),2)*100 AS PERCENT_OVER_80
FROM
  (SELECT COUNTY, CASE WHEN PROOF::NUMERIC >= 80 THEN 1 ELSE 0 END AS OVER_80
   FROM SALES INNER JOIN PRODUCTS
   ON SALES.ITEM=PRODUCTS.ITEM_NO) AS TEMP
GROUP BY COUNTY
ORDER BY 2 DESC;


--BASED ON NUMBER OF SALES, WHAT WERE THE TOP FIVE CATEGORIES OF LIQUOR SOLD IN THE FIVE MOST POPULOUS COUNTIES?

SELECT CATEGORY_NAME, COUNT (*) AS COUNT_SALES
FROM SALES
WHERE COUNTY IN (SELECT COUNTY FROM COUNTIES ORDER BY POPULATION DESC LIMIT 5)
GROUP BY CATEGORY_NAME
ORDER BY 2 DESC LIMIT 5

--WHICH WHISKEY OR VODKA PRODUCTS HAVE SALES > SOME AMOUNT INDICATING SPECIFIC PRODUCTS TO MARKET

SELECT CATEGORY_NAME, VENDOR, DESCRIPTION, SUM(TOTAL)
FROM SALES
WHERE TOTAL > 20000 AND (CATEGORY_NAME ILIKE '%WHISK%' OR CATEGORY_NAME ILIKE '%VODKA%')
GROUP BY CATEGORY_NAME, VENDOR, DESCRIPTION
ORDER BY SUM(TOTAL) DESC

--WHAT PERCENTAGE OF SALES PER COUNTY ARE MORE THAN $100? WHAT ARE THE TOP FIVE COUNTIES IN THIS CATEGORY?

SELECT COUNTY, ROUND (AVG (SALES_100),2)*100 AS PERCENT_100
FROM
(SELECT COUNTY, TOTAL
, CASE WHEN TOTAL > 100 THEN 1 ELSE 0 END AS SALES_100 FROM SALES) TEMP
GROUP BY COUNTY
ORDER BY 2 DESC
LIMIT 5;

--FREMONT IS HIGHEST PROPORTION OF SALES OVER 100, PUSH HIGH QUALITY/HIGH PRICE ITEMS HERE

/*BASED ON ABOVE, I WOULD TARGET MARKETING SPEND TO JACK DANIELS, CROWN ROYAL, ABSOLUTE VODKA
I WOULD TARGET THESE ADS TO THE LOW PERFORMING COUNTIES (IN TERMS OF SALES/CAPITA) OF FREMONT, WAYNE AND DAVIS,
PRIORITIZING HIGHER END WHISKEY AND VODKA PRODUCTS TO FREMONT DUE TO 67% OF THEIR SALES CONTAINING WHISKEY /VODKA PRODUCTS
AND FREMONT IS ALSO HIGHEST PROPORTION COUNTY OF SALES OVER $100 */
